#!/usr/bin/env bash

. _common.sh

pushd "$this_dir" > /dev/null

log "setting up tools"
./setup

log "installing homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || true

log "checking for xcode installation (install via App Store if this fails"
xcode-select -p

log "installing zsh"
brew install zsh

log "adding zsh to /etc/shells"
grep /usr/local/bin/zsh /etc/shells || sudo bash -c "printf '%s\n' "/usr/local/bin/zsh" >> /etc/shells"

log "setting default shell"
sudo chsh -s /usr/local/bin/zsh $USER

log "installing java"
brew install Caskroom/versions/iterm2-beta
brew install Caskroom/cask/witch
brew install Caskroom/cask/bettertouchtool
brew install Caskroom/cask/quicksilver
brew install Caskroom/cask/java
brew install Caskroom/cask/intellij-idea
brew install Caskroom/cask/google-chrome

log "done setting up tools"