#!/usr/bin/env bash

. _common.sh

function install-homebrew {
    log "installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || true
}

function check-xcode-installed {
    log "checking for xcode installation (install via App Store if this fails (or just run git)"
    xcode-select -p
}

function brew-install-apps {
    brew install zsh
    brew install Caskroom/versions/iterm2-beta
    brew install Caskroom/cask/witch
    brew install Caskroom/cask/bettertouchtool
    brew install Caskroom/cask/quicksilver
    brew install Caskroom/cask/dropbox
    brew install Caskroom/cask/java
    brew install Caskroom/cask/intellij-idea
    brew install Caskroom/cask/google-chrome
    brew install Caskroom/cask/1password
    brew install Caskroom/cask/diffmerge
    brew install Caskroom/cask/skype
}

function setup-zsh-shell {
    log "adding zsh to /etc/shells"
    grep /usr/local/bin/zsh /etc/shells || sudo bash -c "printf '%s\n' "/usr/local/bin/zsh" >> /etc/shells"

    log "setting default shell"
    sudo chsh -s /usr/local/bin/zsh $USER
}

function set-defaults {
    log "setting defaults"
    # faster keybaord
    defaults write NSGlobalDomain InitialKeyRepeat -float 10
    defaults write NSGlobalDomain KeyRepeat -int 2

    # ensure that the dock stays hidden
    defaults write "com.apple.dock" autohide-delay -float 10000

    # stop apps reopening on reboot
    defaults write -g ApplePersistence -bool no

    # stop iterm prompting on exit
    defaults write com.googlecode.iterm2 PromptOnQuit -bool false

}

function install-login-script {
    local plist=$( cat ./login.plist | sed 's/$USER/'"$USER"'/' )
    cat > /Users/"$USER"/Library/LaunchAgents/login.plist <<< "$plist"
}

function reboot {
    log "hit enter to reboot"
    read
    sudo reboot
}

function configure-git {
   log "configuring git"
   git config --global push.default simple
}

pushd "$this_dir" > /dev/null

log "bootstrapping"

./setup
check-xcode-installed
configure-git
install-homebrew
brew-install-apps
setup-zsh-shell
install-login-script
set-defaults
reboot

log "bootstrapping complete"