#!/usr/bin/env bash

. _common.sh

cd "$this_dir"
if [ "$GIT_PULL_COMPLETE" != true ]; then
    log "pulling preferences"
    git pull
    export GIT_PULL_COMPLETE=true
    eval "$0"
else
    log "writing idea preferences"
    rsync -azPv \
        "$this_dir/sync/Preferences/IntelliJIdea2016.1/" \
        "$HOME/Library/Preferences/IntelliJIdea2016.1"

    log "writing preferences"

    killall cfprefsd
    cp "$this_dir/sync/Preferences"/*.plist "$HOME/Library/Preferences"
    cp "$this_dir/sync/Preferences/bttdata2" "$HOME/Library/Application Support/BetterTouchTool/bttdata2"

    log "pulling preferences complete"
fi
