#!/usr/bin/env bash

. _common.sh

log "pushing preferences"

log "reading idea preferences"
rsync -azPv \
    "$HOME/Library/Preferences/IntelliJIdea15/" \
    "$this_dir/sync/Preferences/IntellijIdea15" \
    --exclude chrome-user-data \
    --exclude componentVersions \
    --exclude scratches \
    --exclude tasks \
    --exclude options/recentProjects.xml

log "reading iterm2 preferences"
cp "$HOME/Library/Preferences/com.googlecode.iterm2.plist" "$this_dir/sync/Preferences"

cd "$this_dir"
git add -A
git commit -m "syncing prefs"
git push

log "pushing preferences complete"