#!/usr/bin/env bash

. _common.sh

function link_tools {
    log "linking tools"
    local target_dir="$HOME/$( basename "$this_dir" )"
    if [[ -e "$target_dir" ]]; then
        log "$target_dir already exists"
        return
    fi

    log "linking $this_dir to $target_dir"
    ln -sh "$this_dir" "$target_dir"
}

function link_home {
    log "linking home"
    ( cd home && find . -type f ) | while read file; do
        local target_file="$HOME/$file"
        if [[ -e "$target_file" ]]; then
            log "$target_file already exists"
            return
        fi

        local source_file="$this_dir/home/$file"
        log "linking $source_file to $target_file"
        mkdir -p $( dirname  "$target_file" )
        ln -sh "$source_file" "$target_file"
    done
}

link_tools
link_home